name: Build and Publish Docker Image
on:
  push:
    branches:
    - master
    tags:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish image
      run: ./docker-publish -i redpillanalytics/dbt -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
