name: Build and Publish Docker Image
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build and Publish default label
      run: ./docker-publish -i redpillanalytics/dbt -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Publish spark label
      run: ./docker-publish -i redpillanalytics/dbt -t spark -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
